# Generated by Django 5.2.12 on 2026-03-17 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['invoice'], name='payments_pa_invoice_fcb1dc_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_date'], name='payments_pa_payment_1d6e55_idx'),
        ),
    ]
