# Generated by Django 5.2.12 on 2026-03-17 11:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('unit', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='tenant_photos/')),
                ('nationality', models.CharField(default='Indian', max_length=100)),
                ('id_proof_type', models.CharField(blank=True, max_length=50, null=True)),
                ('id_number', models.CharField(blank=True, max_length=100, null=True)),
                ('id_document', models.FileField(blank=True, null=True, upload_to='tenant_documents/')),
                ('permanent_address', models.TextField()),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('pin_code', models.CharField(blank=True, max_length=10, null=True)),
                ('emergency_contact', models.CharField(blank=True, max_length=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Occupancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('billing_type', models.CharField(choices=[('advance', 'Advance'), ('arrears', 'Arrears')], default='advance', max_length=20)),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('daily', 'Daily')], default='monthly', max_length=20)),
                ('check_in_date', models.DateField()),
                ('check_out_date', models.DateField(blank=True, null=True)),
                ('next_due_date', models.DateField()),
                ('security_deposit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('deposit_paid', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allotted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allotted_units', to=settings.AUTH_USER_MODEL)),
                ('subunit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='occupancies', to='unit.subunit')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occupancies', to='unit.unit')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occupancies', to='tenant.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge_type', models.CharField(choices=[('electricity', 'Electricity'), ('food', 'Food'), ('maintenance', 'Maintenance'), ('laundry', 'Laundry'), ('custom', 'Custom')], max_length=50)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('charge_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('occupancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='tenant.occupancy')),
            ],
        ),
    ]
