# Generated by Django 5.2.12 on 2026-03-17 14:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0001_initial'),
        ('unit', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='occupancy',
            index=models.Index(fields=['is_active'], name='tenant_occu_is_acti_4fdb90_idx'),
        ),
        migrations.AddIndex(
            model_name='occupancy',
            index=models.Index(fields=['check_in_date'], name='tenant_occu_check_i_d17700_idx'),
        ),
        migrations.AddIndex(
            model_name='occupancy',
            index=models.Index(fields=['check_out_date'], name='tenant_occu_check_o_b197f6_idx'),
        ),
    ]
