# Generated by Django 5.2.12 on 2026-04-18 09:54

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0004_alter_tenant_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='email',
            field=cloudinary.models.CloudinaryField(blank=True, default=None, max_length=255, verbose_name='tenants'),
        ),
    ]
