# Generated by Django 5.2.12 on 2026-04-18 09:56

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0005_alter_tenant_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='profile_photo',
            field=cloudinary.models.CloudinaryField(blank=True, default=None, max_length=255, verbose_name='tenants_photo'),
        ),
    ]
