# Generated by Django 5.2.12 on 2026-03-17 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
        ('unit', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='unit',
            index=models.Index(fields=['property'], name='unit_unit_propert_7a835c_idx'),
        ),
    ]
