# Generated by Django 5.2.12 on 2026-04-18 09:54

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unit', '0002_unit_unit_unit_propert_7a835c_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitimage',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, default=None, max_length=255, verbose_name='units'),
        ),
    ]
