# Generated by Django 5.2.12 on 2026-05-25 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit', '0003_alter_unitimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='amenities',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
