# Generated by Django 5.2.12 on 2026-04-18 09:54

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='thumbnail',
            field=cloudinary.models.CloudinaryField(blank=True, default=None, max_length=255, verbose_name='properties'),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, default=None, max_length=255, verbose_name='properties'),
        ),
    ]
