# Generated by Django 5.2.12 on 2026-05-25 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_alter_property_thumbnail_alter_propertyimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='has_subunits',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('pg', 'PG'), ('hostel', 'Hostel'), ('shop', 'Shop'), ('flat', 'Flat'), ('office', 'Office'), ('building', 'Building')], max_length=20),
        ),
    ]
